import { app } from '~/config'

export const form = {
  name: null,
  development_type_id: null,
  developer_id: null,
  total_floor: null,
  total_unit: null,
  total_one_bedroom: null,
  one_bedroom_size: null,
  one_bedroom_size_to: null,
  total_two_bedroom: null,
  two_bedroom_size: null,
  two_bedroom_size_to: null,
  total_three_bedroom: null,
  three_bedroom_size: null,
  three_bedroom_size_to: null,
  pent_house_size: null,
  primary_phone: null,
  secondary_phone: null,
  email: null,
  facebook: null,
  province_id: app.default_province,
  country_id: app.default_country,
  province: null,
  district_id: null,
  commune_id: null,
  village: null,
  street_no: null,
  building_no: null,
  direction: null,
  road_con: null,
  road_dir_width: null,
  lat_lng: null,
  image_one: null,
  image_two: null,
  image_three: null,
  image_four: null,
  image_five: null,
  published: true,
  exclusive: false
}
