/* eslint-disable camelcase */
export default () => ({
    status: 'success', // success|failed|updating
    totalResource: 0,
    items: {
        ceiling: [],
        client_sources: [],
        requirement_services: [],
        requirement_results: [],
        listing_purposes: [],
        property_types: [],
        property_type_groups: [],
        data_source: [],
        deed_type: [],
        design_appeal: [],
        direction: [],
        drainage: [],
        electricity: [],
        form_layouts: [],
        flooring_material: [],
        gender: [],
        institute_type: [],
        land_shape: [],
        length_units: [],
        location_appeal: [],
        main_wall: [],
        person: [],
        priority: [],
        road_condition: [],
        roofing: [],
        sewerage: [],
        listing_status: [],
        topography: [],
        price_type: [],
        room_type: [],
        visit_status: [],
        water: [],
        window_frame: [],
        zoning: {}
    }
})
