export const primevue = {
    theme: 'tailwind-light',
    ripple: true,
    components: [
        'AutoComplete',
        'DataTable',
        'Card',
        'Carousel',
        'Column',
        'ColorPicker',
        'InputText',
        'InputSwitch',
        'Dialog',
        'ConfirmDialog',
        'Dropdown',
        'Checkbox',
        'RadioButton',
        'Panel',
        'Calendar',
        'SelectButton',
        'FileUpload',
        'ImagePreview',
        'Tooltip',
        'InputNumber',
        'Toast',
        'Paginator',
        'ProgressBar',
        'Chart',
        'Password',
        'MultiSelect',
        'ScrollPanel',
        'SpeedDial',
        'TabPanel',
        'TabView',
        'Tag',
        'ToggleButton',
        'Galleria',
        'OverlayPanel'
    ],
    directives: ['Tooltip', 'Badge']
}
